### ISSUE TITLE
Unquoted boundary tag in multipart forms may cause request failure

### ISSUE THREAD

**Issue by object** [haf/Http.fs#100]
RFC 2046 says the following:

   _The grammar for parameters on the Content-
   type field is such that it is often necessary to enclose the boundary
   parameter values in quotes on the Content-type line.  This is not
   always necessary, but never hurts. Implementors should be sure to
   study the grammar carefully in order to avoid producing invalid
   Content-type fields.  Thus, a typical "multipart" Content-Type header
   field might look like this:

```
 Content-Type: multipart/mixed; boundary=gc0p4Jq0M2Yt08j34c0p
```

   But the following is not valid:

```
 Content-Type: multipart/mixed; boundary=gc0pJq0M:08jU534c0p
```

   (because of the colon) and must instead be represented as

```
 Content-Type: multipart/mixed; boundary="gc0pJq0M:08jU534c0p"_
```

Since Http.fs often generates boundary tags with non-alpha characters, the tags should be quoted, otherwise the request may fail (and indeed failed when I tested it).

NB! The quotes should only be used in boundary tag definition, not when the boundary tags used to separate form parts.

**Comment by haf** [comment]
Good catch! I made it random to avoid having a 'working but wrong' logic, so I'm glad this was caught.

And the nuget `Http.fs` is released now!

**Comment by object** [comment]
So I guess it's time for 3.0.7 already. :-)

**Comment by haf** [comment]
PR?

**Comment by object** [comment]
I submitted a PR for this. Some unrelated tests fail both on my local machine and in AppVeyor build (see the log here: https://ci.appveyor.com/project/GrantCrofton/http-fs/build/1.5.1.166). I believe this has nothing to do with my PR, I've seen similar exceptions due to conflicting versions of target F# runtime, but what causes it this time I don't know.

**Comment by haf** [comment]
Thanks for your contribution!

**Comment by object** [comment]
Do you plan to release 3.0.7 soon?

**Comment by haf** [comment]
Hmm, yes. I just need to start using `Logary.Facade` in it. Hopefully this evening. Otherwise tomorrow. I do take PRs that auto-release though, like I've done with DotNetZip.Semverd and myself with DotLiquid. In fact, I'm going to start auto-releasing all my F# libs with albacore in the short run.

**Comment by haf** [comment]
v `.7` released due to Hopac having been released with broken dependency.

**Comment by object** [comment]
Cool!
