### ISSUE TITLE
Poor dependency resolution

### ISSUE THREAD

**Issue by neoeinstein** [haf/Http.fs#102]
The latest released version of `Http.fs-prerelease` was on July 15,. It reports a dependency on Hopac (`>= 0.1.3`) I think that the Http.fs package was compiled against Hopac 0.2.1. Now with Hopac 0.3.10 out, a user just declaring a new dependency on Http.fs may end up with a 0.3.x series version of Hopac. Hopac is still pre-v1.0, so it has been making breaking changes on the minor version number. This can lead to some MethodNotFoundExceptions at runtime.

Proposed solution: issue a new version (3.0.6) which is semver bound to the Hopac minor version (`>= 0.3.4, < 0.4.0`) would probably help things, and clarify which version of Hopac you are supporting. I'm just not sure what I need to modify in the `rakefile` to submit a proper PR.

/cc @polytypic

**Comment by haf** [comment]
We should now move over to `Http.fs`. Sorry about the bad communication.

**Comment by haf** [comment]
<img width="817" alt="screen shot 2016-08-19 at 18 45 36" src="https://cloud.githubusercontent.com/assets/193115/17817126/2242d080-663d-11e6-88ad-f96bd974a36d.png">
