### ISSUE TITLE
Occasional exception "forwarded" from Hopac.dll

### ISSUE THREAD

**Issue by object** [haf/Http.fs#103]
This one happens occasionally so I can't get more details on it, but I observed it on multipart posts when the request fails with a single word "forwarded" as the error message. I checked Hopac code and the only place that raises an exception with such error string is "forward" function which unconditionally throws an error:

  let forward (e: exn) : 'x =
    raise (exn ("forwarded", e))

Hmm, it doesn't seem that Http.fs calls this function anywhere, so this might be a Hopac error.

**Comment by polytypic** [comment]
Currently `forward` is called when a job being `run` raises an exception.  Catch the exception and check the [`InnerException`](https://msdn.microsoft.com/en-us/library/system.exception.innerexception%28v=vs.110%29.aspx) to get more details.

**Comment by object** [comment]
I see, this is exception forwarding. I will investigate what kind of inner exception is raised.

**Comment by haf** [comment]
Http.fs should not throw exceptions. If you get exceptions, I'd be very interested in where they come from and interested in catching them inside this lib.

**Comment by object** [comment]
I am also very keen in finding this out because this is a critical piece of our system. I wasn't able to reproduce it right after I reported the issue but I am sure it will happen again. I was occurred pretty frequently last week.

**Comment by object** [comment]
Apparently the inner exception is null (I am logging both outer and inner exception messages and it's only "forwarded" that gets logged). I still need to figure out how this happens.

**Comment by haf** [comment]
If you log with Logary, Logary will reflect on the exception and extract all available data in it.

At least it's an issue with the WebClient and Hopac-specific. But perhaps the inner exception isn't properly set from Hopac when `raise ("forwarded", ex)` is called?

**Comment by polytypic** [comment]
Hmm... It should not be possible for the inner exception to be null:

https://github.com/Hopac/Hopac/blob/1fb867fad2c9a566065effdc4fb8744b43997bdc/Libs/Hopac/Hopac.fs#L41-L42
https://github.com/Hopac/Hopac/blob/1fb867fad2c9a566065effdc4fb8744b43997bdc/Libs/Hopac/Hopac.fs#L509-L511

(`State1` is the exception.)  Note that I've since changed the code to this:

https://github.com/Hopac/Hopac/blob/1f1fec347f9af1d23da9f94b03fdfbc38b646775/Libs/Hopac/Hopac.fs#L506-L508

**Comment by object** [comment]
This is weird indeed. I hope to be able to supply more information soon.

**Comment by object** [comment]
After upgrading to latest versions of Http.fs and Hopac I no longer encounter these exceptions. I will close this issue for now and in case it happens again will repopen it.
