### ISSUE TITLE
Cookie size exceeded

### ISSUE THREAD

**Issue by gusty** [haf/Http.fs#115]
I'm getting this error:

    System.Net.CookieException: The value size of the cookie is '...(large cookie content which is intentionally ommited here)...'. This exceeds the configured maximum size, which is '4096'.
    at System.Net.CookieContainer.Add(Cookie cookie, Boolean throwOnError)
    at System.Net.CookieContainer.Add(Cookie cookie)
    at HttpFs.Client.DotNetWrapper.setCookies@675-1.Invoke(Cookie arg00)

We'll need to handle this situation.

**Comment by haf** [comment]
Sure; but it's a valid error. How do you want to handle it? There are not dependently typed strings in .Net.

**Comment by gusty** [comment]
I don't know. I need to have a look at the code in order to answer your/my own question, but #116 doesn't make it easy.

Thanks for you quick response and the update on the docs, I tried following those steps but got many errors all the time. I need more time to investigate them and I promise will update the doc with the solution when I get there.

I'm a bit surprised about how many steps you need to do to build the solution, seems too much or am I missing something? Many projects have a build.cmd that makes your life easier :)

I'm curious about how dependently typed strings would solve this issue. I mean, I'm getting the cookie set from the website at run-time so can't think of a compile-time feature that would help here.

**Comment by haf** [comment]
The build process is optimised for a setup once - use many scenario – which it successfully removes any friction from. In my case it's very quick to build test and release nugets with albacore warning me on the way if I made a mistake as well as compiling release notes in the nuget.

The RFC forbids larger cookies, so we can't do very much besides making it a documented error.

**Comment by gusty** [comment]
I had a look at the RFC, it makes sense. Thanks !

**Comment by haf** [comment]
You're welcome.
