### ISSUE TITLE
Beginner question: simple example of post

### ISSUE THREAD

**Issue by mariomeyrelles** [haf/Http.fs#117]
Hello, 

After the change to Hopac in this version I'm not really sure if I'm doing things correctly. In my case, I just want to post a simple to server and I felt a little bit overwhelmed when trying to follow the examples because now there are some more things to consider like the idea of "Jobs", "ALT" and so on. On my tests, this request worked perfectly:

```
type ApiHttpResponse = 
    | Ok of string
    | Error of int
    | Exception of Exception



let postAsync url body = 
    async { 
        let req = Request.create Post (Uri url) |> Request.bodyString body
        return job { 
                   let! response = getResponse req
                   let output = 
                       match response.statusCode with
                       | 200 -> 
                           let b = Response.readBodyAsString response |> run
                           Ok b
                       | _ -> Error response.statusCode
                   return output
               }
               |> run
    }
```

Do you think this is a good approach? Is this really async as I am expecting to be? 

If I would give a suggestion, I would try to change a little bit the documentation to go from easier examples to more complex examples.

Kind regards,
Mário Meyrelles

**Comment by haf** [comment]
Hi Mário,

No, not really. Jobs are capable of being run as cooperative multithreading, like async normally implies a wish of.

You should really only ever call `run` at the composition root at the `main` method of your program.

I added a sample to `HttpFs.SamplePostApplication`, and here it is reproduced for you, as well:

```fsharp
open System
open HttpFs.Client
open Hopac

type ApiHttpResponse =
    | Ok of body:string
    | Error of statusCode:int
    | Exception of e:exn

let sampleGetBody urlStr bodyStr : Async<ApiHttpResponse> =
    let resp =
        Request.create Post (Uri urlStr)
        |> Request.bodyString bodyStr
        |> getResponse

    resp |> Alt.afterJob (fun resp ->
        // if we don't cancel the request, let's read the body in full
        match resp.statusCode with
        | x when x < 300 ->
            resp
            |> Response.readBodyAsString
            |> Job.map Ok
        | x ->
            Error resp.statusCode
            |> Job.result
    )
    |> Alt.toAsync
```

Full source https://github.com/haf/Http.fs/blob/master/HttpFs.SamplePostApplication/Program.fs

**Comment by mariomeyrelles** [comment]
Hello @haf ,

Thanks for your very fast answer. It works like a charm! Many thanks!

To be honest I tried to read the documentation from https://github.com/Hopac/Hopac/blob/master/Docs/Programming.md#introduction and other sources like https://neoeinstein.github.io/blog/2016/04-08-hopac-getting-started-with-jobs/index.html. But both sources are somewhat complex to understand at a first glimpse.

Can you give some guidance on main concepts that we should understand before trying to use HttpFs? 

Kind Regards,
Mário Meyrelles

**Comment by haf** [comment]
The main thing to understand is `Alt.afterFun` approx = `Job.map` and `Alt.afterJob` approx = `Job.bind`.

Also, never use `run` except at the composition root.

Alt inherits Job.

If you want an async instead, use `Alt.toAsync` or `Job.toAsync`.

With HttpFs you need to dispose the Response. And if you get the body, you need to dispose its stream.

That's mostly it.

**Comment by mariomeyrelles** [comment]
Thanks for the response! I'll try to study this matter in greater detail in the coming weeks. Also I'll take a look at Concurrent ML material in order to understand the rationale behind Hopac and so on. Let's see if I can learn a little bit more :)

Kind Regards,
Mário
