### ISSUE TITLE
Question: Load Http.fs in .fsx

### ISSUE THREAD

**Issue by ridderholt** [haf/Http.fs#123]
I'm trying to develop an script using F# where I would like to use Http.fs to make a request. But I'm having troubles loading the Hopac dependency when I run the .fsx file locally I get the error:
```
The type referenced through 'Hopac.Job`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'Hopac.Core'.
```
I have installed Http.fs using nuget into a folder named "packages" and my code looks like this:

```
#r "./packages/Hopac.0.3.21/lib/net45/Hopac.dll"
#r "./packages/Hopac.0.3.21/lib/net45/Hopac.Core.dll"
#r "./packages/Http.fs.4.1.0/lib/net40/HttpFs.dll"

open Hopac
open HttpFs.Client

let body = Request.createUrl Get "http://www.somesite.com"
            |> Request.responseAsString
            |> run

printf "%s" body
```
Don't know if it's just a simple mistake by me, but I don't get this error for other nuget packages when I use them in a .fsx file.

**Comment by haf** [comment]
You need to mark the folder where Hopac is as a search folder;

```fsharpi
#I "packages/Hopac/lib/net45"
#r "Hopac.dll"
#r "Hopac.Core.dll"
#r "packages/Http...."
```
