### ISSUE TITLE
Why can't handle Set-Cookie header in response

### ISSUE THREAD

**Issue by vik-borisov** [haf/Http.fs#129]
In response, I get the Set-Cookie header, but I can not find it in the properties 'response.Cookies', 'response.Headers'

In httpfs.fs I found these lines:

``
      | "Set-Cookie"                  -> None
``

Why can not I process the Set-Cookie header in response?

**Comment by haf** [comment]
Because the call to http fs should be referentially transparent, so if the response to a request changes future requests, they are not that, any longer.

But building a stateful abstraction could be done. Do you know how?

**Comment by vik-borisov** [comment]
Can i parse Set-Cookie header, and put the cookies in Response.Cookies?

**Comment by haf** [comment]
Yes that would work. PR that and unit tests. :)

**Comment by vik-borisov** [comment]
Why do you use RAKE to build instead of FAKE? For the F# project  - F# build engine =)

**Comment by haf** [comment]
Because albacore is better at authoring nugets. See discussion https://github.com/haf/expecto/pull/175#issuecomment-304928578 for details. I don't mind switching to an equally competent system, but I'm reluctant to leave my own code behind if it will mean I have to spend more time in maintenance.

**Comment by vik-borisov** [comment]
Can you release this feature?
