### ISSUE TITLE
Removes the double quotes from the boundary part of the content type

### ISSUE THREAD

**Issue by galatrash** [haf/Http.fs#133]
Recently we saw some failing tests due to having double quotes in the boundary string of the content type. If we issue the same requests without the double quotes, they pass.

Please fix this line of code from
```
| Some b -> yield! [ ";"; " boundary="; sprintf "\"%s\"" b ]
```
to this
```
| Some b -> yield! [ ";"; " boundary="; b ]
```

**Comment by haf** [comment]
@galatrash-at-dnn Sorry, I don't remove things because some piece of code that you haven't linked to fails to parse requests according to the RFC https://www.ietf.org/rfc/rfc2046.txt –  see p18.
