### ISSUE TITLE
Add Function to Set ServerCertificateValidationCallback on Underlying HttpWebRequest Object

### ISSUE THREAD

**Issue by HoraceGonzalez** [haf/Http.fs#14]
Would it be possible to provide a function to your library that allows a ServerCertificateValidationCallback delegate to be specified for the HttpWebRequest object that's created in HttpClient.toHttpWebRequest? This would be useful in cases where you'd want to "pin" a public key (see https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning).

**Comment by haf** [comment]
I suggest this:
- A module for Http TLS validation
- Each validation has its own validator-function `HttpCertChain -> Choice<unit, string>` in this module
- There's a function compose that takes a list of functions of the above signature and returns a function of the above signature
- There's an internal function that overrides the `ServerCertificateValidationCallback` function
- There's a public function that lets you give your own composed list and in turn calls the above two functions `compose` and `internal setCallbackOnWR`

You could have a look at https://github.com/haf/miTLS/ to see a proven way to validate TLS certificates and find functions for each of the validation checks.

**Comment by haf** [comment]
Please PR if you want this.
