### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by ghost** [haf/Http.fs#144]
Hello,

I have a project using 4.1.2 via nuget, it appears that from 4.1.2 to 5.0.0 `Request.autoFollowRedirectsDisabled` was removed, which is preventing me from upgrading. It appears that looking at the code, the entire concept of disabling redirect following has been removed. 

The doco has not been updated to reflect this change.

It seems the change that removed it was here:

https://github.com/haf/Http.fs/blob/375ead66ae5da41359df2621d49838165a3b3493/HttpFs/HttpFs.fs#L372

**Comment by ivpadim** [comment]
@xenocons you will need to use the createWithClient method.

```
  let handler = new HttpClientHandler(UseCookies = false)
  handler.AllowAutoRedirect <- true
  let client = new HttpClient(handler)
  client.DefaultRequestHeaders.Clear()

Request.createWithClient client ...
```

**Comment by ghost** [comment]
As a drop in for existing code:


```
    let httpClientWithNoRedirects () =
        let handler = new HttpClientHandler(UseCookies = false)
        handler.AllowAutoRedirect <- false
        let client = new HttpClient(handler)
        client.DefaultRequestHeaders.Clear()
        client

    module Request =
        let autoFollowRedirectsDisabled h = 
            let noRedirectClient = httpClientWithNoRedirects ()
            { h with httpClient = noRedirectClient }
```

This should work, be aware you will be calling new HttpClient effectively twice per actual request

**Comment by haf** [comment]
@xenocons It would be great if you could paste this in the README via the edit-on-github functionality!

**Comment by ghost** [comment]
@haf, I have updated the readme. Perhaps we should consider implementing Request.createUrlWith to modify the HttpClientHandler before init as a parameter to allow for this:

`Request.createUrlWith Post "https://www.a.com" (fun handler -> handler.AllowAutoRedirect <- false)`   

I am not sure how often this would be needed though, and it may be better to put the responsibility on the user to prevent API clutter.

**Comment by ghost** [comment]
No need for apologies, thanks for walking me thru it!
