### ISSUE TITLE
Get custom response header

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#151]
```
        let aid = response.headers |> Map.find (ResponseHeader.Custom "aggregate-id")
```

**Comment by ivpadim** [comment]
> ```
>         let aid = response.headers |> Map.find (ResponseHeader.Custom "aggregate-id")
> ```

I noticed we have a NonStandard response header for that. But I agree the Custom name makes more sense.

**Comment by ivpadim** [comment]
I'm closing this then and no change was made to avoid any naming conflicts.

For non standard response headers we can use the following:

```

let aid = response.headers |> Map.find (ResponseHeader.NonStandard "aggregate-id")

```

**Comment by haf** [comment]
@ivpadim Why close it? We still can't read custom headers from the response?

**Comment by ivpadim** [comment]
Yes we can get custom Response Headers using the NonStandard ResponseHeader.

You can see the code I wrote in the comment, please let me know if that works for you to close it.

**Comment by haf** [comment]
You're right.
