### ISSUE TITLE
How would I determine content-length, content-type, etc without actually downloading the file?

### ISSUE THREAD

**Issue by rm2** [haf/Http.fs#158]
I tried to do:
```
    Hopac.Hopac.job {
      use! response = HttpFs.Client.getResponse request
      let status = response.statusCode
      let contentType = response.headers.[HttpFs.Client.ResponseHeader.ContentTypeResponse]
      return status, contentType, response.headers
    }
    |> Hopac.Hopac.run
```
but even though I didn't use `HttpFs.Client.Response.readBodyAsBytes response` or `response.body.CopyToAsync` the job still runs until the full body is returned?

**Comment by haf** [comment]
This might be a bug in how the HttpClient is set up; if you followed the advice of the previous thread you may not have told your instance of HttpClient not to read the body.

**Comment by haf** [comment]
Now my google fu fails me, but the above is what I remember from previously... Do ping us when you solve your issue; the code of this repo should be easy to read; so it comes down to how HttpClient does it.

**Comment by rm2** [comment]
Turns out all I had to do was change `getResponse` to `getEventSourceResponse`. `getEventSourceResponse` eventually calls `getEventSourceResponseNoException` which calls `httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cts)` instead of `httpClient.SendAsync(request, cts))` which is what `getResponse` eventually calls. And
supplying `HttpCompletionOption.ResponseHeadersRead` means:

 "The operation should complete as soon as a response is available and headers are read. The content is not read yet." as opposed to the default "The operation should complete after reading the entire response including the content."

So now I have:
```
    Hopac.Hopac.job {
      use! response = HttpFs.Client.getEventSourceResponse request
      let status = response.statusCode
      let contentType = response.headers.[HttpFs.Client.ResponseHeader.ContentTypeResponse]
      return status, contentType, response.headers
    }
    |> Hopac.Hopac.run
```
and that immediately returns with just the headers.

Not sure how the name `getEventSourceResponse` infers Return-as-soon-as-headers-are-read??? :P

**Comment by haf** [comment]
Hi,

Yeah, if you could see how that function works and perhaps make its 
logic configurable, it would be great. It's a good workaround though.

Regards,
Henrik
