### ISSUE TITLE
Body not sent with DELETE request

### ISSUE THREAD

**Issue by cmeeren** [haf/Http.fs#167]
Http.fs does not send content with DELETE requests.

The HTTP spec doesn't define semantics for content in DELETE requests, but it's not prohibited, and it's required for certain popular API specs, e.g. [removing members from relationships in JSON:API](https://jsonapi.org/format/#crud-updating-to-many-relationships).

[Possibly helpful SO thread/answer](https://stackoverflow.com/a/46780507/2978652)

**Comment by ivpadim** [comment]
@cmeeren version 5.4.0 is out! Please upgrade.

**Comment by cmeeren** [comment]
Excellent, thanks! 👍
