### ISSUE TITLE
Remove dependency on FSharpX to simplify things

### ISSUE THREAD

**Issue by relentless** [haf/Http.fs#17]
Http.fs uses a source file from fsharpx for the Async stuff (AsyncStreamReader.fs).  This isn't a problem functionality-wise, but it does have a couple of down sides:
- Makes licensing more complicated.  FSharpX isn't the only 3rd party library used, but it does have the most restrictive licence (Apache 2.0).
- Makes code more complicated (two files instead of one).
- Means we have to ignore code in coverage, or get low coverage results.

**Comment by haf** [comment]
Done
