### ISSUE TITLE
Don't commit packages/

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#42]
![screen shot 2015-01-02 at 20 12 20](https://cloud.githubusercontent.com/assets/193115/5598748/b4c4d6da-92bb-11e4-9163-bc3aa4e8b14e.png)

zzzzz

**Comment by relentless** [comment]
I like including the packages as I like to have everything needed to build it there in the repository. I don't really want to rely on NuGet, and I'm not sure they respect Semantic Versioning in terms of not auto-installing something whose major version has changed (a breaking change to the API). But I can see it would be better to have a smaller download.

What does anyone else think, is out time to take the 3rd party DLLs out of source control and rely on NuGet?

**Comment by haf** [comment]
paket.lock locks down the versions though, so you have to be explicit when you upgrade major version.

**Comment by relentless** [comment]
OK, thanks - let me look into that and get back to you.

--- Original Message ---

**Comment by haf** [comment]
ping

**Comment by haf** [comment]
Closed in favor of PR.

**Comment by relentless** [comment]
I'm still not convinced it's a good idea not to check the binaries into source control.  I mean, it's not like you don't have to download them anyway, you just do it at a different time, and it increases dependencies down the line (NuGet being up, for example).

This blog discusses the things I don't like, plus others:
http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful/

**Comment by haf** [comment]
Well, this isn't NuGet package restore, it's Paket so it's less buggy. Let's address his points:
- How often I clone on a train or on 3G/4G? Every day, different repositories. And it's not just the initial pull that's expensive; any pull of changed binary data forces a complete download. And then it's not quick at all. In fact, on about 15 minutes I'm heading over to a café and then I'm on mobile. Yesterday I sat all day at a café with bad internet, and that's when I interacted with this repo.
- "even if we had used package restore they would not have been empty"; true, but they would have been two orders of magnitude less in size; 600 KiB versus 60 MiB. Two orders of magnitude larger code is a lot; especially considering that 50% of my SSD is code + temporary binary assets (about 128 GiB), so I'd rather have it use less. I have to clean my harddrive from not-really-junk stuff every month, and since I have a MacBook Pro, changing the harddrive costs at least 12000 kr not to mention the opportunity cost of actually changing it, going to the store, being without my laptop for a week (!!). If you factor that into the equation, we're probably talking an excess of 100 000 kr.
- If NuGet is down, Paket goes towards the cache folder, so it's still quick.
- If NuGet is down in my own workflow, it falls over to my private MyGet repo which has a cache for all the nugets I have ever downloaded.
- Finally, if NuGet is down I might choose to write code that doesn't depend on NuGets
- Since we're talking open source, the points about internal package restore are null and void

So in my mind I've countered every single point that is relevant in his article.

YMMV, though, but I'm fairly certain of my own mileage.

**Comment by haf** [comment]
Oh, and for me, the largest issue with binaries is that I can't be certain that they are legit; because I can't inspect them! How do I know that you (you = anyone in open source, in any repository that I clone and use) haven't planted a back-door in one of these DLLs??
