### ISSUE TITLE
Consider renaming assembly to match project name?

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#57]
Currently the assembly is named 'HttpClient' but the project 'Http.fs', which causes some friction when one is new to the project.

Possibly consider renaming the DLL to match the name of the project, or otherwise close this issue.

**Comment by relentless** [comment]
Yeah, it makes sense to rename the assembly.  The major version needs updating now anyway due to a breaking API change, so this would be a good time to do it.

**Comment by haf** [comment]
Done in PR.
