### ISSUE TITLE
`Transfer-Encoding: chunked,chunked`

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#58]
```
2) Test Failure : HttpClient_IntegrationTests+Integration tests.all of the response headers are available after a call to getResponse
     Expected string length 7 but was 15. Strings differ at index 7.
  Expected: "chunked"
  But was:  "chunked,chunked"
  ------------------^
```

**Comment by haf** [comment]
I had another look at this; it's probably due to the underlying Http infra defaulting to 'chunked' encoding. The correct way to format multiple values for a single header, is comma-separating them, so from an API perspective, everything is alright.

I think it might be a mistake to test this header as an application header as it's not controlled by the application, but by the web server. Therefore I'm removing the lines pertaining to setting it; but I'm open to suggestions.

**Comment by relentless** [comment]
I think the test is valid as it's checking that the response headers get returned when they are set, but we can update it to work with different values.
