### ISSUE TITLE
Don't version releases together with source code

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#63]
This is an anti pattern because:
- it dramatically increases the checkout time for CI and human builds of the project
- you already have the history on NuGet and MyGet
- it's worth more having reproducible builds across version than to save binary artifacts, see also https://bugzilla.xamarin.com/show_bug.cgi?id=26842
- you can save those binary artifacts in github releases
- git is not adapted primarily for binary large artifacts
- it's basically a copy of the code, slightly modified, so viewing diffs of them doesn't make much sense and this disturbs the human review-workflow

**Comment by relentless** [comment]
I wanted to have a way for people to be able to get the versioned assembly without downloading a NuGet, especially for F# scripts. But I wasn't aware of GitHub releases at the time, so I guess that can be used for the purpose.

**Comment by haf** [comment]
Great =). Merging the PR will close this issue automatically.
