### ISSUE TITLE
Consider switching to a non-reflection based testing framework

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#66]
I would recomend Fuchu. The upsides are many:
- you don't have to have a specific runner for unit tests; just run the console project
- you can compose test-values like any other value, which means you can create awesome test DSLs (I have a proprietary one that's not yet open sourced that makes it very easy to test event-sourced read models and domains for example)
- fast moving than NUnit, which seems to be very stalled in terms of features
- much better code inside testing framework, if you venture into it, clean F# as opposed to huge C# methods with mutability
- XamarinStudio doesn't lock up when running it
- parallel test runner
- supports F# modules

Drawbacks:
- less community
- fewer 'nice' Asserts - but you can go pretty far with what's in there
- another API
- doesn't support TestCase (but that's not used in this code-base) - but has a nice integration with FsCheck so it's stronger on the random-testing side than NUnit is

**Comment by haf** [comment]
PS; I'll show you what it looks like for this code-base.

**Comment by relentless** [comment]
Sorry, mainly AFK this weekend, will reply to your suggestions soon.

WRT different test framework, I'd be happy to give something else a try. Would want to look at how well this integrates with VS and the build tool though. I imagine most people run the tests through an integrated runner, and good info for test failures in the build is useful.

Grant

--- Original Message ---

**Comment by haf** [comment]
You just set startup project to be the test assembly. It doesn't integrate with VS at all. The error messages are better though, because the asserts are more granular.

**Comment by relentless** [comment]
Fair enough.  Well if it improves things on Xamarin that's a step forward - it's not like many people contribute to this project, so if it requires contributors to do something a bit different to what they might be used to it's not a big problem.

**Comment by haf** [comment]
We have Fuchu for the unit tests now. Closing.
