### ISSUE TITLE
Setting header multiple times now allowed?

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#67]
There was the 'chunked,chunked' issue; and now I found a unit-test for setting a header multiple times;

```
If the same header is added multiple times, throws an exception
```

Should this be the case? Isn't it more in line with HTTP to comma-separate the header values? See e.g. how the Set-Cookie header from the server works.

**Comment by Muhomorik** [comment]
It looks like it is a user check, but some headers may be set implicitly by HttpWebRequest/HttpResponse. 
For example chunked is dependent from Content-Length header and buffer. And request/response doesn't check for duplicates before.

**Comment by Muhomorik** [comment]
The thing is... complicated. 
Some headers are allowed to be duplicated, but it must be possible to concatenate them to a comma-separated list, remaining the order in which header are received.

Basically, there should be a list of known multi-headers. In list - append, others - take first value. User-defined headers - let user fix it . Regarding #76.

**Comment by relentless** [comment]
I see - I must admit, I never actually looked into setting the same header multiple times, I just put this in to warn people about (what I thought was) a mistake.  Sounds like it needs a bit of work.  (Although I've never heard about anybody actually trying to do this.)

**Comment by haf** [comment]
I'm changing the logic to overwrite duplicate headers instead.
