### ISSUE TITLE
Bug in `withBasicAuthentication` for non-Latin-1 username/password combos

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#73]
From the code:

```
Encoding.GetEncoding(ISO_Latin_1).GetBytes(username + ":" + password)
```

This is unsafe if username or password is outside the Latin-1 charset, right? How is GetBytes supposed to map UTF8-four-byte data into 2-byte data? It can't.

**Comment by haf** [comment]
Btw, this is not a bug according to the spec, but:

```
Also relevant, no current browser does this. They use utf-8 (Chrome, Opera), iso-8859-1 (Safari), the system code page (IE) or something else (like only the most significant bit from utf-8 in the case of Firefox).
```

I think we should go with UTF8. More reading: http://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication

**Comment by relentless** [comment]
Yes, I remember looking into this at the time.  It's not obvious what the right thing to do is, but 8859-1 seems to be the best bet according to the spec.  If browsers go with utf-8 it's probably OK.

**Comment by haf** [comment]
Fixed in PR.
