### ISSUE TITLE
Install failed targeting Profile47

### ISSUE THREAD

**Issue by paulyoung** [haf/Http.fs#83]
`Could not install package 'Http.fs 1.5.1'. You are trying to install this package into a project that targets 'portable-net45+sl50+win', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Is there anything preventing Http.fs from supporting Profile47?

**Comment by relentless** [comment]
That's the PCL, right?  Http.fs uses WebRequest/Response, which isn't PCL compliant.  We've spoken of swapping that out for something else, which could potentially make it portable, but I don't know if or when that might be.

There's a related discussion here about fsharp.data (which doesn't seem to be is PCL compliant): https://github.com/fsharp/FSharp.Data/issues/93

**Comment by paulyoung** [comment]
That's correct, Profile47 is a PCL profile.

@relentless seems like we already discussed some things there :smile:
