### ISSUE TITLE
Support HMAC signing requests

### ISSUE THREAD

**Issue by screamish** [haf/Http.fs#84]
Love this library!

One thing I've needed to do recently is HMAC signing HTTP requests, but I couldn't think of a very elegant way to do it with Http.fs.

I wrote this function

``` fsharp
let hmacSign signFunction (request:HttpClient.Request) =

    let encode (s:string) = HttpUtility.UrlEncode(s)

    let getQueryString request = 
        request.QueryStringItems
        |> Option.map 
            (List.fold (fun q item -> sprintf "%s%s%s=%s" q (if q = "?" then "" else "&") (encode item.name) (encode item.value)) "?")
        |> Option.getOrDefault

    let signedUrl =
        let b = UriBuilder(request.Url)
        match b.Query with
        | "" | null -> b.Query <- (request |> getQueryString)
        | _ -> ()
        b.Uri.AbsoluteUri |> signFunction

    { request with Url = signedUrl; QueryStringItems = None}
```

Obviously this has to be called as the last thing before calling of the request -> response functions. Can you think of an elegant way of integrating this into Http.fs, is it even the kind of feature you'd want?

**Comment by relentless** [comment]
Hi @screamish, glad you like it.

I've never used HMAC requests, but if all you need's a function perhaps you could set that at any point during creation of the request then use it when you come to actually use it? e.g.

```
createRequest Get "http://somesite.com" 
|> withHmacSignature mySigningFunction
|> withWhatever
|> getResponse
```

Googling it a bit, it seems like HMAC signing is used in different ways in different situations (OAuth, Amazon, Twitter, etc.), which might make it a bit tricky to support it as a general mechanism.  For example, it looks like some schemes encode the querystring, encode the body, encode specific headers, add new keys/values, etc., and some don't.

Do you know much about it, @haf?

**Comment by screamish** [comment]
Yeah, sorry, I should have provided some more context. My example is only one form of HMAC as applied to HTTP. I was only hoping to see if you had any ideas about how to best support something like this with the Http.fs API. I could easily wrap all of the (Request -> Response _) functions something like this

``` fsharp
let getResponseWithSigning = (withHmacSignature mySigningFunction) >> getResponse
```

but I'm thinking you guys will have far more elegant ideas than me :)

**Comment by haf** [comment]
I wrote a library for http signing: https://github.com/logibit/logibit.hawk/ have a look and see if it fits your needs -- there's the Client module which does what you're after.

As for elegance, it's in the eye of the beholder ;). I think it's very elegant that values compose like you've just shown, personally. I do composition just like you, e.g. here https://github.com/haf/mailgun/blob/master/src/Mailgun.Api/Api.fs
