### ISSUE TITLE
What version should I use?

### ISSUE THREAD

**Issue by lefthandedgoat** [haf/Http.fs#85]
It seems like the documentation on the front page is not for version 1.5.1.  To see working example apps for 1.5.1 I am having to revert back to an older commit (which is ok now that I have figured it out)

Version 2.0 + on nuget has a warning that `A temporary nuget until 2.0 is released. Don't depend on!`

Should I not depend on that nuget package being there or not rely on the 2.0+ code?

I am going to start writing some integration tests and I would like to start with the 'best' version =)

**Comment by relentless** [comment]
Hi, yes sorry it's a bit confusing at the moment.  Unless you want to use any of the new features of 2.0 (multipart requests and such), you're probably better off sticking to 1.5.1.

We're currently working on 2.0, but it won't be backwards compatible, so we want to make sure it's fairly stable before releasing it on NuGet.  Unfortunately the only documentation is the readme and sample apps, which have been updated with the 2.0 code.

**Comment by lefthandedgoat** [comment]
Ok thanks! I will run with 1.51 and use the sample apps from the old commit as reference.
