### ISSUE TITLE
AssemblyInfo.fs is missing on disk. Build fails.

### ISSUE THREAD

**Issue by Muhomorik** [haf/Http.fs#86]
Seems like AssemblyInfo.fs is inside the project file, but not on disk. Build fails.
I am surprised that build is not failing, because mono and studio does.

> FSC: error FS0225: Source file '/HttpFs/AssemblyInfo.fs' could not be found
> 
>    0 Warning(s)
>    1 Error(s)
> ---------------------- Done ----------------------
> Build: 1 error, 0 warnings

Although it can be removed, assembly will be compiled with no information, i.e., in the Details tab of the file properties you will see no name, no description, version 0.0.0.0, etc.

I suggest to put it back ;)

**Comment by relentless** [comment]
If you build it from the script it should work (build.bat/build.sh).  But I think we need to sort it out so it can be build from VS as well.

**Comment by Muhomorik** [comment]
Looks like it fails at linux / Monodevelop as well. Would be nice to get support for two major IDE's back.
