### ISSUE TITLE
Request: Add target for profile 259

### ISSUE THREAD

**Issue by saosebastiao** [haf/Http.fs#87]
Profile 259 is quickly becoming the profile of choice for Xamarin projects, and I would like to be able to use this library in my own PCL259 project.

**Comment by relentless** [comment]
Hi, there are no current plans to make Http.fs PCL-compliant, as it would mean a fairly big internal rewrite to not be based on WebRequest/Response, although if anyone wants to take it on that would be fine with me.

See https://github.com/relentless/Http.fs/issues/83.

**Comment by haf** [comment]
Yes, please, PR.

**Comment by object** [comment]
While profile 259 is still the most popular one for use with Xamarin applications, the future choice seems to be a profile 111, Microsoft even started deprecating profile 259 in some of their portables libs (e.g. ODataLib version 7). So I guess the right thing would be to add support for both profiles or go straight to 111.

**Comment by haf** [comment]
+1
