### ISSUE TITLE
Anyone want to take over Http.fs?

### ISSUE THREAD

**Issue by relentless** [haf/Http.fs#88]
I don't really have the time or inclination to do much else with it - I don't have any functional need for it beyond what it already does, and I have other learning projects on the go, so if anyone else would like to take it to the next level (or even just tidy everything up to get to a solid v2.0), let me know.

cc @haf @rodrigovidal @sergey-tihon @Sergeeeek

**Comment by haf** [comment]
Hello Grant,

I hope I haven't caused you too much frustration with my PRs – when I start using a project it can be like drinking from a firehose sometimes – I may appear relentless.

I appreciate getting the offer (cc?), but right now I'm very busy with both Suave and Logary, not to mention qvitoo.com. I think I've done a lot of the required clean ups already though, and I think you should publish what's here as v2.0. If you don't publish, you'll never have people using the v2 branch of the code, so there will be no PRs and no progress. Often it's more important just to ship it, than to have it absolutely polished.

My current plan right now is to spend as little time as possible on this repo until I have a requirement for either finished the Proxy module of Suave or until I have implemented my structurally typed TCP/IP library based on Hopac for F# (perhaps written in F*), on which I can re-implement Http.fs in a way that's correct by construction.

I'm also in the process of re-implementing EventStore.Client.FSharp as a general purpose CQRS framework that lets you do pull-based stream processing using Hopac and do O(1) update- and read- tranducer-based read-models for Suave...

And then there's Logary which is turning 4 versions old in the next couple of months as I finished the data flow network that will be the foundation for crash-only/continuously persisting metrics and reservoirs.

Again, I'm sorry I can't help you, but I would vote you to release v2 as it stands and rely on the community to improve it. If you could still take the time to respond to pull requests and do superficial code review that would be much appreciated.

**Comment by relentless** [comment]
Yes you're right, I'll try and get v2 out soon.  I just want to try and get the breaking changes done first.

**Comment by treefrog00** [comment]
what needs tidying up for 2.0? If you need a maintainer I'd be happy to maintain it. Also, small world - I used to work in Leeds and I think you probably vaguely know both one of my previous managers and someone I vaguely know through caving.

**Comment by relentless** [comment]
Hi James, sorry for the delay.

If you're up for taking the library forward, that would be great.  I still think it's viable (use it pretty often myself), but I just don't have the time at the moment.  Functionality-wise I don't think much needs doing, but there's quite a lot that needs sorting behind the scenes.

WRT v2.0, functionality-wise it's just a few things related to the API:
- Naming the assembly Http.fs instead of HttpClient
- Making the functions more consistent (e.g. some use records as parameters some just take primitives)
- I don't really like how it reads with 'createRequest ... getResponse', that could be made more fluent/nicer

Anything that doesn't break the API in a non-backwards-compatible way can be done later.

However, there are quite a few things behind the scenes that I think need sorting.  If these don't affect the API it's not a must for 2.0, but it's hard to know for sure.  These include:
- Getting the tests passing on Mono
- Re-enabling the commented-out/ignored tests
- Simplify the build to work with VS & Fake (e.g. get rid of Rake)
- Get rid of Suave or Nancy in the integration tests, one web framework is enough
- Decide on one test framework (e.g. NUnit or Fuchu)

The documentation's a bit of a mess now, that could do with sorting out too - the main point was to make it easy to do HTTP with F#, but there are now details of a load of advanced things that most people won't care about.  So maybe that stuff should be split out into an 'advanced' page or something.

Anyway, those are my thoughts, but if you'd like to take it on then I imagine you'll have our own ideas about what's important and how to proceed.

**Comment by treefrog00** [comment]
My PR seems to fix the mono issue. I don't use mono myself but Travis says my PR branch is green, it was just a treat-warnings-as-errors thing. 

I can do the other things as and when I have time and I'm not working on something else. Should I just keep submitting PRs?

Also, a couple of questions:
1. As far as I can tell Logging.fs is never used?
2. I can probably make a local build work using FAKE without too many problems, but does anything also need changing on Appveyor or Travis?

Thanks!

**Comment by haf** [comment]
Given that the code now is mostly of my authorship now and that we use this lib a lot, I want to voice some ideas. 

First of all there doesn't seem to be a good idea to do busy work by moving to FAKE when the project is already using albacore which is easier to work with. Similarly a case could be made that it is a good thing for a http client to be tested against multiple http servers, so why create busy work by replacing Nancy for suave or vice versa? 

The largest defect isn't in what command you build the software  with but the software as it is for users to use. For example, there is no good/unified response disposal mechanism. The Logging.fs file I added should be integrated, not removed. The client should be extended to allow authentication and logging filters to be transparently added to the client. It would be beneficial to add disk buffering for large responses and to test the client with above four GiB files. 

Because these are real world use cases, and they are needed. As opposed to doing busy work of refactoring tests that aren't broken.

**Comment by treefrog00** [comment]
I suspect changing to FAKE would only take a couple of hours work, whilst installing and learning the syntax of albacore would take about the same. But I realise you wrote both albacore and much of this project and that there are more useful things to do than argue about build systems.

**Comment by haf** [comment]
By the way; we have some parallel development going on at https://github.com/haf/Http.fs/pull/3 and https://www.nuget.org/packages/Http.fs-prerelease/, so if we can figure out common objectives, then we can go far :)

**Comment by haf** [comment]
I've been thinking of this library; that we use daily and if you add me and @lapponiandevil as a contributor we can start shipping our improvements into the main library.

**Comment by relentless** [comment]
I'm happy to add you as contributors, but one thing I'd like to be sure of is that you'll continue to ensure the basic use case of making simple requests is as easy as possible, which was the point in the first place.  (Indeed, the tag line probably should have been something like 'Simple, functional HTTP requests for F#).

For example making people use a Uri object when creating the initial request instead of just specifying it in a string is the opposite of this, as is's making the simple use case (as needed, I would assume, by the majority of users) more complex and making yours simpler.

**Comment by Muhomorik** [comment]
I wonder if it is possible to leave an "old" design and make it small and tidy. Just wrapper around HttpWebRequest and put it into the separate package and inline everything.
The maintainability cost would be zero because it is just a wrapper.

**Comment by haf** [comment]
I agree with easy, we differ on implementation, but from what I understand of what you're saying, stringly typed APIs are "easy"? We could of course provide those APIs too.

I normally think that typed APIs are easy, because they don't compile if they're used in error, and what's easier than having the compiler correct you as you type?

Is it only the request Uri or other pieces you would prefer are stringly typed, too? I'm absolutely not against having that _as well_.

**Comment by relentless** [comment]
@Muhomorik I'd say that's pretty much what Http.fs is, I mean we don't advertise the HttpWebRequest underpinnings too much but it's unlikely to be replaced.  It would be cool to have a new http client for F#, perhaps written ground-up to be PCL compliant and so on, but IMO we'd be better off leaving Http.fs as it is and having a new project for that new thing.

**Comment by relentless** [comment]
@haf I'm not saying the strings in themselves make it easy, but "http://google.." |> crateRequest ... is easier than Uri("http://google..") |> crateRequest, and both are invalid if the string is incorrect.  Or course, if you already have a Uri the situation is different, but I think we should optimise for the simpler and more likely scenario of a string and have the Uri-based scenario as a secondary option.

**Comment by haf** [comment]
I'm curious; what common scenarios do you use this from? Because I never keep strings around if they contain data I compute with.

**Comment by relentless** [comment]
Calling things from FSI, PoCs, little utilities, that kind of thing
