### ISSUE TITLE
Incorrect withQueryStringItem in README.md

### ISSUE THREAD

**Issue by gsscoder** [haf/Http.fs#89]
Form README.md the signature seems to be accept two string and a request, but it really needs a NameValue record.

Anyway, thanks for sharing this great lib!

Giacomo

**Comment by relentless** [comment]
Yes, sorry the readme is out of sync with the version on NuGet - I'll try and sort that out soon.

**Comment by gsscoder** [comment]
@relentless, if you want some help I can do it for you with a PR. At your discerption... :)

**Comment by relentless** [comment]
I've added a link to the readme from version 1.5.1, hopefully that will do until I've got v2 out on NuGet.

**Comment by gsscoder** [comment]
Perfect! Excellent work... :)
