### ISSUE TITLE
Read response encoding from meta tag?

### ISSUE THREAD

**Issue by relentless** [haf/Http.fs#9]
Some HTML (and XML) pages specify the character encoding in the page and not in the header, e.g.

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">

or

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

At the moment, the user would have to specify these manually using 'withResponseCharacterEncoding' (assuming the default encoding didn't work), but it should be possible to parse this information and use it to specify the proper encoding.  It involves decoding the header, which should be US-ASCII, finding the encoding (if specified), then decoding the whole thing using the encoding.

However this will add a fair bit of complexity and will slow the processing down somewhat, so it's not clear if it's a good idea to add it.

**Comment by haf** [comment]
It's probably not a good idea: trust what the browser sends.

XML is always supposed to be UTF-8 encoded.

HTML, not so. It's not up the client to start reading into the body of the response. That's for the client's user, the programmer ;)

...and the example given is not a meta-tag.
