### ISSUE TITLE
How do we go about moving 2.X to nuget?

### ISSUE THREAD

**Issue by MattHartz** [haf/Http.fs#92]

**Comment by relentless** [comment]
I need to publish it, but there are a few things with the API I'd like to change before making it 2.0.  Although to be fair, I've been saying that for ages and not making much progress..

Also as per https://github.com/relentless/Http.fs/issues/88, @Haf's been progressing it in a fork, so we need to decide what to do about integrating that.

**Comment by haf** [comment]
Like I've said before, I can help maintain it while considering your wish of stringly typed interfaces, if you give me access. Meanwhile @MattHartz v2.4 is at nuget key `Http.fs-prerelease`.

**Comment by relentless** [comment]
I added you as a collaborator

**Comment by WilliamBerryiii** [comment]
@haf mind if @MattHartz puts in a PR for the NTLM update into your 2.0 pre-release package (https://github.com/relentless/Http.fs/pull/91)?

**Comment by haf** [comment]
@WilliamBerryiii Go ahead, it's here: https://github.com/haf/http.fs

**Comment by haf** [comment]
@relentless thanks

**Comment by haf** [comment]
@relentless Could you add me to the nuget so I can update it?

**Comment by relentless** [comment]
I added you as an owner - says pending approval, not sure who has to approve it though.

**Comment by haf** [comment]
@relentless thank you!

**Comment by haf** [comment]
v2 released
