### ISSUE TITLE
Making requests cancellable i.e. Alts rather than Jobs?

### ISSUE THREAD

**Issue by polytypic** [haf/Http.fs#94]
First, thanks for the great work on this lib!

I noticed recently that you've switched to using Hopac. Trying out Http.fs I noticed that pretty much all of the operations are implemented as `Job<_>`s.  Have you considered implementing operations such as `getResponse` and `readBodyAsString` as `Alt<_>`s so that the operations could be cancelled via Hopac's alternative mechanism?

The [Cancellation with Negative Acknowledgments](https://github.com/Hopac/Hopac/blob/master/Docs/Alternatives.md#cancellation-with-negative-acknowledgments) doc illustrates the idea by wrapping `Async<_>` computations as `Alt<_>`s.

Related to this I started working on [some improvements](https://github.com/Hopac/Hopac/pull/100) to Hopac's `Task<_>` interop.  (You can implement cancellable `Task<_> -> Alt<_>` conversion outside of Hopac's core, but typically it is possible to reduce the number of allocations (and improve perf) substantially by making a core implementation of such ops. It would likely also make sense to revisit the `Async<_>` interop ops as those can likely also be optimized further.)

**Comment by haf** [comment]
That's a good idea. I'm thinking it may be a good idea to skip the numerous wrappings if we can. The underlying web request supports the BeginXXX and EndXXX pattern, and I have a feeling that using AsyncGetResponse first uses the Async function that returns Task, that in turn uses the Begin-End pattern; so we'd wrap Begin-End in Task in Async in Alt, which seems a bit like overkill.

There's also an Abort function on the request object, that would seem like a good choice; then we'd avoid calling the EndXX function if the Abort function was called.

**Comment by haf** [comment]
How about

``` fsharp
    let getResponseNoException (request : HttpWebRequest) : Alt<Choice<HttpWebResponse, Error>> = 
      Alt.withNackJob <| fun nack ->
        let rI = IVar ()

        let rJ : Job<Choice<HttpWebResponse, Error>> =
          job {
            try
              let! resp =
                Job.fromBeginEnd request.BeginGetResponse request.EndGetResponse
              return Choice.create (resp :?> HttpWebResponse)

            with
            | :? WebException as wex ->
              if wex.Response <> null then
                return Choice.create (wex.Response :?> HttpWebResponse)
              elif wex.Status = WebExceptionStatus.RequestCanceled then
                return Choice.createSnd Error.Cancellation
              else
                // TODO: handle the other status enum values
                return Choice.createSnd (Error.IOException (wex :> exn))

            | :? IOException as ioex ->
              return Choice.createSnd (IOException (ioex :> exn))

            | :? System.Net.Sockets.SocketException as sex ->
              return Choice.createSnd (IOException (sex :> exn))
          }

        nack >>- fun () -> request.Abort()
        |> Job.start
        >>-. rI
```

**Comment by haf** [comment]
Closing in favour of #95
