### ISSUE TITLE
Support for application/json with no base64 conversion in form file data

### ISSUE THREAD

**Issue by object** [haf/Http.fs#97]
My app generates multipart forms, and one of the files is a small JSON that I submit as a string:

FormFile("json", ("meta.json", ContentType.Parse "application/json" |> Option.get, Plain <| "{ some JSON data }"))

The library then converts JSON data into base64-encoded string but the server on the other side expects plain string so the request fails. I checked the source and it's only "plain/text" that is sent verbatim, anything else includion "application/json" is base64-encoded.

Since "applicaiton/json" happens to be text, shouldn't this type be sent without encoding? If for some reasons this is a bad idea can content transfer encoding be open to accept the value from the client?

**Comment by haf** [comment]
The client can't sniff you files to see what they are.

You can probably make it post the file as binary though? That way it can be interpreted as text.

A failing test showcasing what you're expecting would be great.

**Comment by object** [comment]
Unfortunately I can't provide a failing test because this happens during our integration with some external service. The service requires JSON files to be uploaded using StringContent and application/json as content type. If we set content type to text/plain, the request fails, if we put base64 string in StringContent and specify transfer encoding type as base64, the request fails. So it must be a combination of StringContent of a plain text and application/json as content type. Not flexible (I already reported this to them), but such things happen, so my question is should the library allow higher level of control for such stuff?

**Comment by haf** [comment]
I think [File, Plain](https://github.com/relentless/Http.fs/blob/master/HttpFs/HttpFs.fs#L475) is what you need. Could you write a unit test that sends a file, any file, to Suave and have Suave read the contents of the post as plain text?

**Comment by object** [comment]
Agree. File, Plain server the purpose, and Http.Fs works fine with that. It's just the server I am integrating with is not flexible and demands that I send plain text but specify application/json as the content type (and Http.fs encodes application/json using base64).

Now I believe that this scenario is too special, Http.fs conventions are reasonable and I just need developers of that service to relax their treatment of uploaded files. So we don't need to do anything here. Thanks for quick response.

**Comment by haf** [comment]
How about https://github.com/relentless/Http.fs/blob/master/HttpFs/HttpFs.fs#L705 and using Binary? I think that will work. After all, if your file is utf8 then so will its binary representation be.

**Comment by object** [comment]
I just tried that and it didn't. For every such case I used Fiddler to verify that Http.fs correctly generated the payload. And it did. In total I was able to use the following alternatives:
1. Plain with string and content-type text/plain
2. Plain with base64-encoded string and content-type application/json
3. Binary with byte array
4. StreamData with octet stream

All 4 cases worked fine with Http.fs, payload is correctly generated. But neither of them was accepted by the server at our integration endpoint because for JSON files it demanded following combination:
1. Plain with string and content-type application/json.

And this one is the only one not supported by Http.fs. If it's not text/plain it must use base64 encoding.

Should this be addressed?

I am not sure. Http.fs has reasonable defaults and providing possibility to overload everything may take away some of its simplicity.

Having said that, I may ask: is this reasonable that application/json strings are sent as base64-encoded and not as plain text? Shouldn't json, html and xml strings be transferred as plain text? What is the benefit of encoding text content as base64 strings?

**Comment by haf** [comment]
No, there's no upside, only a 30% transfer overhead. But where do we stop sending plain-text? application/xml, too? Or open document formats? Or ...

**Comment by object** [comment]
Yes I know, then next question is where to draw the borderline. So current criteria (only text/plain is sent verbatim) is at least clear. But it's too strict from practical point of view, because there is bunch of content types that can (and probably should) also be sent as clear text. So it's a choice between clear distinction and being practical (and optimal with regards to payload). Your choice :-)

**Comment by haf** [comment]
Actually, if you PR a list of content types you feel should be sent as text then I'll merge that.

**Comment by object** [comment]
Sounds good. But I need to do a little research first.
